### ISSUE TITLE
Example was written with a previous version?

### ISSUE THREAD

**Issue by wizard699** [SvenTiigi/WhatsNewKit#11]
There are problema in  SharedTheme with WhatsNewKit 1.0.2.
Perhaps the example was implemented with a different version????

**Comment by wizard699** [comment]
More detail:  the file SharedTheme.swift in example, with the last versione (from CocoaPod) of WhatsNewKit, have this error:   

Missing argument for parameter 'backgroundColor' in call

**Comment by wizard699** [comment]
All is ok.  I've update to the release 1.1.2.
Thanks

**Comment by SvenTiigi** [comment]
Hey @wizard699 

Perfect 👍

You might also take a look at the new release [`1.1.3`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.1.3) which has a completely refactored and updated Example Application.

**Comment by wizard699** [comment]
Thanks a lot

Inviato da iPhone

**Comment by wizard699** [comment]
But, at the moment, from Cocoapod, there is only the 1.1.2 version. It’s correct?

Inviato da iPhone

**Comment by SvenTiigi** [comment]
Hey @wizard699 

the latest available Version of WhatsNewKit via CocoaPods is Version `1.1.3`.

![bildschirmfoto 2018-10-21 um 10 43 05](https://user-images.githubusercontent.com/11733014/47264832-42b9ad00-d51e-11e8-8203-7fabafc6c587.png)

Please make sure your Podfile is set to:

```ruby
# All Version up till 1.2.0
pod 'WhatsNewKit', '~> 1.1.0'

# Or retrieve always the latest Version
pod 'WhatsNewKit'
```
