### ISSUE TITLE
v1.1.4 breaks KeyValueWhatsNewVersionStore

### ISSUE THREAD

**Issue by saldous** [SvenTiigi/WhatsNewKit#14]
After upgrading, WhatsNew keeps displaying every time I launch the app. Downgraded back to 1.1.3, problem goes away.

`print(keyValueVersionStore.has(version: .current()))
`
always shows false with v1.1.4

**Comment by SvenTiigi** [comment]
Hey @saldous 

Thanks for your bug report 🙌

The problem should be solved with Version [`1.1.5`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.1.5)
