### ISSUE TITLE
two-line title on iphone SE

### ISSUE THREAD

**Issue by furiosFast** [SvenTiigi/WhatsNewKit#15]
there is a problem with the two-line title (and a high font, example 37) on iphone SE: the second line does not appear

**Comment by SvenTiigi** [comment]
Hey @furiosFast 

Thanks for your bug report.

Have you tried to reduce the font size for smaller screen sizes like the iPhone SE?

Maybe you calculate the font size based on the screen scale:
[https://developer.apple.com/documentation/uikit/uiscreen/1617836-scale](https://developer.apple.com/documentation/uikit/uiscreen/1617836-scale)

Currently the `TitleView` height is set to `20%` of the screen height and does not adjust its content based on the Label text to avoid reducing the `yOrigin` of the `ItemsView`.

**Comment by SvenTiigi** [comment]
Closing due inactivity. Feel free to re-open the issue at any time.
