### ISSUE TITLE
Detail button was missing on iPad in landscape

### ISSUE THREAD

**Issue by BenBeng** [SvenTiigi/WhatsNewKit#16]
I was running the demo on iPad Pro 11 simulator(iOS 12), and the detail button was missing when iPad was in landscape, and split mode.

Also, I found the items view was too left, and the completion button was too long when using on iPad in landscape. Maybe you can give an option to use `tableView.cellLayoutMarginsFollowReadableWidth = true` and some other layout change to make it more readable on iPad.

![simulator screen shot - ipad pro 11-inch - 2019-01-31 at 23 53 40](https://user-images.githubusercontent.com/2141846/52066441-87d88b00-25b3-11e9-88ee-95801304a1ef.png)

**Comment by SvenTiigi** [comment]
Hey @BenBeng 

Please have a look at the new Release [`1.1.6`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.1.6) 

It contains an improved Layout for iPhone/iPad and API's to configure the Layout insets to your needs.

![simulator screen shot - ipad air 2 - 2019-02-02 at 14 34 29](https://user-images.githubusercontent.com/11733014/52165414-c7f95400-2700-11e9-9dfb-22dd196bd6e4.png)
