### ISSUE TITLE
Please Provide Support for Swift Package Manager , Thanks

### ISSUE THREAD

**Issue by rajatsha90271** [SvenTiigi/WhatsNewKit#23]
## WhatsNewKit Environment

- WhatsNewKit version:
- Xcode version:
- Swift version:
- macOS version running Xcode:
- Dependency manager (Carthage, CocoaPods, Manually):

## What did you do?

> ℹ Please replace this with what you did.

## What did you expect to happen?

> ℹ Please replace this with what you expected to happen.

## What happened instead?

> ℹ Please replace this with of what happened instead.

**Comment by SvenTiigi** [comment]
Hey @rajatsha90271,

Please check out the latest release [`1.2.0`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.2.0) which adds support for Swift Package Manager
