### ISSUE TITLE
[iOS 13] ItemsView scrollview too large when using content Mode .fill or .center

### ISSUE THREAD

**Issue by mattbarker016** [SvenTiigi/WhatsNewKit#24]
## WhatsNewKit Environment

- WhatsNewKit version: 1.2
- Xcode version: Xcode-beta 11.0 beta 5
- Swift version: Swift 5
- macOS version running Xcode: macOS 10.14.6
- Dependency manager (Carthage, CocoaPods, Manually): CocoaPods

## What did you do?

Launched the WhatsNewViewController in iOS 13 with a `itemsView.contentMode` of `.center` or `.fill`.

## What did you expect to happen?

All the items to fit on the screen.

## What happened instead?

The itemsView scrollView went off the screen, with too much space between each itemView. The below screenshots are using an `.fill` with some insets for the itemsView on an iPhone XR simulator.

**iOS 12.2**

<img src=https://user-images.githubusercontent.com/8039928/62845981-973f3c00-bc9a-11e9-97a8-c46f284f9446.png height=600>

**iOS 13.0**

<img src=https://user-images.githubusercontent.com/8039928/62845991-a2926780-bc9a-11e9-8bbe-a2ce84f62e99.png height=600>

**Comment by SvenTiigi** [comment]
Hey @mattbarker016 

Thanks for your bug report 👍

I will definitely have look at this with the newest Xcode 11 beta to find a solution for it.

**Comment by SvenTiigi** [comment]
Hey @mattbarker016 

Please check out the branch [feature/iOS-13](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/iOS-13) I've pushed a bug fix for your reported problem.

Let me know if this bug fix works for you ✌️

**Comment by mattbarker016** [comment]
Yep, works great!
