### ISSUE TITLE
CompletionButton Height

### ISSUE THREAD

**Issue by zboralski** [SvenTiigi/WhatsNewKit#25]
It would be nice to be able to set the height of the completion button. If the goal of this project was to be consistent with the welcome screens that were added to Apple's own apps then the completion button is way too tall.

**Comment by zboralski** [comment]
@SvenTiigi could you make the completion button's interface accessible ?

**Comment by zboralski** [comment]
I switched to the `feature/button-customization` branch and used the following configuration to match iOS 13's Welcome Screen style:

```swift
config.completionButton.titleFont = .systemFont(ofSize: 16)
config.completionButton.insets.bottom = 50
config.completionButton.cornerRadius = 12
config.completionButton.customization = { button in
    button.contentEdgeInsets.bottom = 11
    button.contentEdgeInsets.top = 11
}
```

**Comment by SvenTiigi** [comment]
Hey @zboralski,

I'm looking forward to merge the `feature/button-customization` branch soon to the `master` branch so that you can switch to an official release 👌

**Comment by SvenTiigi** [comment]
Hey @zboralski 

FYI: The branch [feature/iOS-13](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/iOS-13) now contains the latest design update according to the current iOS 13 style.

<p align="center">
<kbd>
<img src="https://user-images.githubusercontent.com/11733014/63704905-5adc1600-c82c-11e9-91a1-810c4d333a8c.png" width="50%" alt="Simulator Screen Shot - iPhone Xs">
</kbd>
</p>

**Comment by zboralski** [comment]
The height of the continue button is much smaller in iOS 13 though.
