### ISSUE TITLE
Animations & iOS 13

### ISSUE THREAD

**Issue by jminutaglio** [SvenTiigi/WhatsNewKit#26]
## WhatsNewKit Environment

- WhatsNewKit version: 1.2.0
- Xcode version: Version 11.0 (11A420a)
- Swift version: 5
- macOS version running Xcode: 10.14.6
- Dependency manager (Carthage, CocoaPods, Manually): CocoaPods

## What did you do?

In the iOS 13 beta, the animations in WhatsNewKit don't show (due to changes in 13 and how push screens are rendered)

## What did you expect to happen?

using:
`                self.present(whatsNewViewController, animated: true)
`

in 12x - animations are fine
in 13x - animations do not render

using: 
`                self.navigationController?.pushViewController(whatsNewViewController, animated: true)
`
in 13x - animations are fine, but "back" is displayed at top of whatsNewViewController

**Comment by SvenTiigi** [comment]
Hey @jminutaglio,

Thanks for your bug-report 👍

Please check out the [iOS-13](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/iOS-13) feature branch which now contains a fix that the animations are triggered correctly when the `WhatsNewViewController` is presented in iOS 13.

**Comment by jminutaglio** [comment]
ty!  the 13 branch resolved what I was seeing. (and fixes some other general layout issues) - looks great.

**Comment by jminutaglio** [comment]
do you plan to merge the 13 branch back here when 13 comes out?  And/or what is the release plan to get the fixes in the main branch?  (so updates can come via Cocoapods?). ty!

**Comment by SvenTiigi** [comment]
Hey @jminutaglio,

Please check out the latest release [`1.3.0`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.3.0) 🥳

**Comment by jminutaglio** [comment]
thank you so much!!!  Your kit is awesome!!!!
