### ISSUE TITLE
Follow iOS 13 Dark Mode Settings

### ISSUE THREAD

**Issue by joeljfischer** [SvenTiigi/WhatsNewKit#29]
## WhatsNewKit Environment

- WhatsNewKit version: 1.3.0
- Xcode version: 11.0
- Swift version: 5.1
- macOS version running Xcode: 10.14.6
- Dependency manager (Carthage, CocoaPods, Manually): Cocoapods

## What did you do?

Use the default WhatsNewKit configuration

## What did you expect to happen?

The coloring would follow iOS 13 dark mode

## What happened instead?

I had to manually set colors to follow dark mode.

**Comment by SvenTiigi** [comment]
Hey @joeljfischer 

Thanks for opening an issue for WhatsNewKit 👍

Dark-Mode-Support for the default Themes will be implemented on the [`feature/dark-mode-support`](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/dark-mode-support) branch. The feature branch will be merged into the master and published with next release as soon as possible.

**Comment by SvenTiigi** [comment]
Hey @joeljfischer 

Please check out the latest release [`1.3.1`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.3.1) which now supports Dark-Mode for predefined Themes 👍

**Comment by feodormak** [comment]
Hey,
The dark mode support implementation does not respond to runtime changes to device dark mode setting changes.
