### ISSUE TITLE
Disable tint for item images

### ISSUE THREAD

**Issue by ammerzon** [SvenTiigi/WhatsNewKit#31]
## WhatsNewKit Environment

- WhatsNewKit version: 1.3.1
- Xcode version: 11.2
- Swift version: 5.1
- macOS version running Xcode: 10.15.1
- Dependency manager (Carthage, CocoaPods, Manually): Carthage

## What did you do?

I created a new WhatsNewController and inserted three items with an image. 

## What did you expect to happen?

The actual assets are displayed without the tint color.

## What happened instead?

The images are all tinted. Is it possible to disable this behaviour?

<img width="169" alt="Screenshot 2019-11-13 at 10 59 13" src="https://user-images.githubusercontent.com/7319168/68753219-efbd0700-0604-11ea-9afa-70332ddae164.png">

**Comment by SvenTiigi** [comment]
Hey @ammerzon,

In default the `autoTintImage` of the `ItemsView` configuration is set to `true`.

You can disable it by simply setting `autoTintImage` to `false`.

```swift
configuration.itemsView.autoTintImage = false
```

**Comment by ammerzon** [comment]
Thx for your quick answer. Now it works.
