### ISSUE TITLE
Colors do not respond to runtime changes to device Dark Mode setting

### ISSUE THREAD

**Issue by feodormak** [SvenTiigi/WhatsNewKit#32]
## WhatsNewKit Environment

- WhatsNewKit version: 1.3.1
- Xcode version: 11.1
- Swift version: 5
- macOS version running Xcode: 10.15.1
- Dependency manager (Carthage, CocoaPods, Manually): CocoaPods

## What did you do?

> ℹ 
- Configured completion button background colour with my own custom UIColor instance supporting Dark Appearance
- Change the device Dark appearance setting in Simulator via Settings & Xcode Environment Overrides

## What did you expect to happen?

> ℹ Colours to update to the corresponding dark/light appearance shade

## What happened instead?

> ℹ Completion button background colour remained in the colour it was initialised with.

**Comment by SvenTiigi** [comment]
Hey @feodormak,

Thanks for your bug report.

I've pushed a fix https://github.com/SvenTiigi/WhatsNewKit/commit/704c647c90b4a50e683468ed8827d0b5b357fd27 on the [`develop`](https://github.com/SvenTiigi/WhatsNewKit/tree/develop) branch.

Please checkout the `develop` branch and let me know if this resolve your issue.

```ruby
pod 'WhatsNewKit', :git => 'https://github.com/SvenTiigi/WhatsNewKit.git', :branch => 'develop'
```

If everything works fine the fix will be included in the next release of WhatsNewKit 👌

**Comment by feodormak** [comment]
Hi @SvenTiigi ,
Thanks for the quick fix, it works, but from what I see, it is not limited to the completion button. The images of the Items are not changing colors too.

**Comment by SvenTiigi** [comment]
Hey @feodormak,

Thanks for your feedback please try it again with the latest commit of the `develop` branch

**Comment by feodormak** [comment]
@SvenTiigi , it works! thanks for the quick updates!

**Comment by SvenTiigi** [comment]
Perfect 👍

The fix will be included in the next release of WhatsNewKit
