### ISSUE TITLE
Statusbar hidden option (enhancement)

### ISSUE THREAD

**Issue by StefaniOSApps** [SvenTiigi/WhatsNewKit#35]
current its not possible to set a flag to hide statusbar without a subclass of WhatsNewViewController.

**enhancement**
`config.prefersStatusbarHidden = true`

**Comment by SvenTiigi** [comment]
Hey @StefaniOSApps,

Thanks for your feature requests 👍 

The `prefersStatusbarHidden` configuration option has been implemented (https://github.com/SvenTiigi/WhatsNewKit/commit/5c3711344025227cd77def93f5bd1409aecb9bdb) and pushed to the [`develop`](https://github.com/SvenTiigi/WhatsNewKit/tree/develop) branch.

The flag will be officially available with the next release of WhatsNewKit.

**Comment by StefaniOSApps** [comment]
thanks

**Comment by SvenTiigi** [comment]
Hey @StefaniOSApps,

please have a look at the new release [`1.3.2`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.3.2) of WhatsNewKit which now adds the option to hide the status-bar ✌️
