### ISSUE TITLE
How to fix Layout Error while using WhatsNewKit Library in Swift 5?

### ISSUE THREAD

**Issue by christophriepe** [SvenTiigi/WhatsNewKit#39]
Hey,

I ran into an error while using WhatsNewKit. I posted a Question on StackOverflow. Here is the link: [https://stackoverflow.com/questions/61372170/how-to-fix-layout-error-while-using-whatsnewkit-library-in-swift-5](url)

Can you think of a reason why this is happening to me? 

Thanks a lot for your help in advance.

**Comment by SvenTiigi** [comment]
Hey @christophriepe,

it seems like you are using a non transparent image or loading the UIImage via the provided name fails this is why the image get tinted in its full bounds.

If you want to disable the default autoTintImage behaviour you can simply change the ItemsView configuration.
```swift
configuration.itemsView.autoTintImage = false
```

As the ItemsView is centered it seems like you are setting the `ItemsView.ContentMode` to `.center` the default behaviour as seen in the example application is `.top`.

```swift
// ContentMode Top
configuration.itemsView.contentMode = .top

// ContentMode Center
configuration.itemsView.contentMode = .center

// ContentMode Fill
configuration.itemsView.contentMode = .fill
```

Please provide a code snippet of your WhatsNewViewController configuration and presentation in order to identify the misconfiguration.

**Comment by christophriepe** [comment]
Thanks for your answer @SvenTiigi.

Here is my code for the configuration: 

```swift
let theme = WhatsNewViewController.Theme { configuration in
    configuration.completionButton.backgroundColor = UIColor.yellow
    configuration.completionButton.titleColor = UIColor.black
            
    configuration.itemsView.contentMode = .top
}
let config = WhatsNewViewController.Configuration(theme: theme)
```

> I now chose the example images in the Example folder but this wasn't the issue. It is still looking the same way as before.

<img width="391" alt="Bildschirmfoto 2020-04-23 um 18 06 48" src="https://user-images.githubusercontent.com/42490623/80122327-ad253080-858d-11ea-9b8f-35d5e4d08f7d.png">

> To see the whole source code for this WhatsnewViewController see the linked StackOverflow Question, as well as for the error messages.
_https://stackoverflow.com/questions/61372170/how-to-fix-layout-error-while-using-whatsnewkit-library-in-swift-5_

I hope you guys can see something I can't. Thanks a lot for your help in advance.

**Comment by SvenTiigi** [comment]
Hey @christophriepe,

I've created an example app and added your provided code snippet.

![Bildschirmfoto 2020-04-23 um 18 47 40](https://user-images.githubusercontent.com/11733014/80126162-fcba2b00-8592-11ea-8be2-ddbec54a2c4e.png)

The ItemsView is correctly displayed at the top position.
Please try the same with a small example app to encapsulate the bug.

It might be that somewhere in your code the ItemsView Configuration gets set to `center`.

**Comment by christophriepe** [comment]
Thanks for your answer @SvenTiigi, that fixed the first problem I had.

> However in all examples the `Item View` takes the **whole available space** like in the image below:

<img width="295" alt="Bildschirmfoto 2020-04-23 um 18 56 21" src="https://user-images.githubusercontent.com/42490623/80127339-77377a80-8594-11ea-84be-3b5e035bc13f.png">

> Why is my `Item View` (or the one in the example app of your last post)  only taking more or less a quarter of The available space?

**Is there any configuration to let the `Item View` fill out all the available space?**

**Comment by SvenTiigi** [comment]
To fill the available space along the axis

```swift
configuration.itemsView.contentMode = .fill
```
[https://github.com/SvenTiigi/WhatsNewKit#contentmode-](https://github.com/SvenTiigi/WhatsNewKit#contentmode-)

Additionally, you can make use of the Insets API to modify the size of the ItemsView

[https://github.com/SvenTiigi/WhatsNewKit#insets](https://github.com/SvenTiigi/WhatsNewKit#insets)

**Comment by christophriepe** [comment]
Thanks, @SvenTiigi, its working now!
