### ISSUE TITLE
Squished layout on iPad in multitasking

### ISSUE THREAD

**Issue by lvandal** [SvenTiigi/WhatsNewKit#45]
## WhatsNewKit Environment

- iOS version: 14.0
- WhatsNewKit version: 1.3.6
- Xcode version: 12.0
- Swift version: 5.0
- macOS version running Xcode: 10.15.6
- Dependency manager (SPM, Carthage, CocoaPods, Manually): SPM

## What did you do?

Displaying the WhatsNew view with default layout values on iPad in multitasking

## What did you expect to happen?

The layout should consider the trait collection

## What happened instead?

The layout is being squished

`private func showWhatsNew() {
        // Initialize WhatsNew
        let versionStore: WhatsNewVersionStore = KeyValueWhatsNewVersionStore()
        
        var configuration = WhatsNewViewController.Configuration(
            theme: .default
        )
        configuration.tintColor = UIColor(named: "someTintColor")!
        configuration.itemsView.imageSize = .preferred
        
        let whatsNew = WhatsNew(
            // The Title
            title: SSKLocalizedString("STR_WHATS_NEW"),
            // The features you want to showcase
            items: [
                WhatsNew.Item(
                    title: "XYZ",
                    subtitle: "Blah blah",
                    image: UIImage(systemName: "bolt.fill")
                ),
                ...,
                ...,
            ]
        )

        // Initialize WhatsNewViewController with WhatsNew
        if let whatsNewViewController = WhatsNewViewController(
            whatsNew: whatsNew,
            configuration: configuration,
            versionStore: versionStore) {
            self.present(whatsNewViewController, animated: true)
        }
    }`

![ipad-layout](https://user-images.githubusercontent.com/157723/93915145-923e2000-fcd5-11ea-9b69-0f6fd154b53f.png)

**Comment by SvenTiigi** [comment]
Hey @lvandal 

Thanks for your bug report and sorry for the delayed response I was on vacation.

Please checkout the feature branch [`trait-collection-fix`](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/trait-collection-fix) and let me know if this resolves your issue.

**Comment by lvandal** [comment]
Yes, it is now fixed. Thanks so much!

**Comment by SvenTiigi** [comment]
Perfect 👍 
I will leave a comment as soon as the bug fix is available within a new release of WhatsNewKit

**Comment by SvenTiigi** [comment]
Hey @lvandal 

The bug fix is now available with the new release of WhatsNewKit [`1.3.7`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.3.7)
