### ISSUE TITLE
SwiftUI support?

### ISSUE THREAD

**Issue by joehinkle11** [SvenTiigi/WhatsNewKit#46]

**Comment by SvenTiigi** [comment]
Hey @joehinkle11 

Support for SwiftUI is currently in development.
Check out the feature branch: [`feature/swift-ui`](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/swift-ui)

**Comment by SvenTiigi** [comment]
Hi @joehinkle11

The new version [2.0.0](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/2.0.0) of WhatsNewKit now supports SwiftUI ✌️
