### ISSUE TITLE
Feature Request | Padding inside of ItemView

### ISSUE THREAD

**Issue by Britishfrog** [SvenTiigi/WhatsNewKit#50]
Hi Sven!

Love the framework for this :D Was wondering if there was a way to affect the padding inside of each ItemView?

Thanks!

**Comment by SvenTiigi** [comment]
Hi @Britishfrog 

Thanks for your bug report.

Currently `WhatsNewKit` is limited to either adjust the `insets` of the `ItemsView` itself via:
https://github.com/SvenTiigi/WhatsNewKit/blob/2750b869363652b178eee757f54b5e7063a93ebc/Sources/Configuration/WhatsNewViewController%2BItemsView.swift#L46

or setting the `contentMode` to `.center` to increase the spacing between each cell.
https://github.com/SvenTiigi/WhatsNewKit/blob/2750b869363652b178eee757f54b5e7063a93ebc/Sources/Configuration/WhatsNewViewController%2BItemsView.swift#L40

But it would be a great addition to configure the spacing between each cell.
I will check if this feature can be added to the next release of `WhatsNewKit` 👌

**Comment by Britishfrog** [comment]
Excellent stuff! Very excited about this showing up in the next release :) For now my workaround is using new lines strategically through the descriptions and titles.

On a separate note, I noticed that images set when `contentMode` is `.center` tend to clip over a certain size. It would be nice if the images were constrained inside of the tableview so that they aspect fit. No pressure though ;)

**Comment by SvenTiigi** [comment]
Hi @Britishfrog,

WhatsNewKit has been updated to a new major version [`2.0.0`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/2.0.0) with extended support for SwiftUI, UIKit and AppKit.

The new version includes some major breaking changes but also a new `WhatsNew.Layout` API which allows you to customize the padding/spacing between the presented features

```swift
// Increase the spacing of the feature list
WhatsNew.Layout.default.featureListSpacing = 100
```

You can find more information about the new Layout API in the [`README.md`](https://github.com/SvenTiigi/WhatsNewKit/tree/master#layout).
