### ISSUE TITLE
Truncated text on iOS 14

### ISSUE THREAD

**Issue by AndrewBennet** [SvenTiigi/WhatsNewKit#52]
## WhatsNewKit Environment

- WhatsNewKit version: 2.0.0
- Xcode version: 13.2.1
- Swift version: 5.5.2
- macOS version running Xcode: 12.1
- Dependency manager (SPM, Manually): SPM

## What did you do?

Presented a WhatsNewKit view controller on a iOS 14 simulator

## What did you expect to happen?

The text to not be truncated.

## What happened instead?

The text was truncated. See attached screenshot.
<img width="561" alt="Screenshot 2022-01-09 at 11 32 41" src="https://user-images.githubusercontent.com/2078225/148697922-6e8d9335-6b80-4a6c-90d0-e48567337d26.png">
Produce by using the following code:
```swift
WhatsNewViewController(whatsNew:
    WhatsNew(
        title: .init(text: .init("Whats New in Reading List")),
        features: [
            .init(
                image: .init(systemName: "shuffle"),
                title: .init("Shake to Choose"),
                subtitle: .init("Shake your device to choose your next book")
            ),
            .init(
                image: .init(systemName: "hammer.fill"),
                title: .init("Improvements and Fixes"),
                subtitle: .init("Various performance improvements and bug fixes")
            )
        ]
    )
)
```
Note, this does not occur on iOS 15 simulators. I have seen similar issues in SwiftUI before, requiring the use of `.fixedSize()`...

**Comment by SvenTiigi** [comment]
PR https://github.com/SvenTiigi/WhatsNewKit/pull/53 has been merged
