### ISSUE TITLE
Cannot Add a package dependency

### ISSUE THREAD

**Issue by DogandElk** [SvenTiigi/WhatsNewKit#56]
## WhatsNewKit Environment

- WhatsNewKit version: 1.3.0
- Xcode version:13.3.1
- Swift version: SwiftUI 3
- macOS version running Xcode:
- Dependency manager (SPM, Manually):

## What did you do?

> I attempted to add a package dependency in Xcode for a SwiftUI project but the url you provided is not recognized

**Comment by DogandElk** [comment]
I also attempted to navigate to the Xcode project then select Swift Packages, then clicked the “+” icon and searched for WhatsNewKit. But it could now be found.

**Comment by SvenTiigi** [comment]
Hi @DogandElk,

Could you please provide a repo where the described issue can be reproduced?

I've tested on my side and wasn't able to reproduce the issue.

<img width="1082" alt="Bildschirmfoto 2022-05-16 um 19 53 47" src="https://user-images.githubusercontent.com/11733014/168653688-035a76fd-4f6f-43ee-b9e4-a2549808d911.png">

<img width="624" alt="Bildschirmfoto 2022-05-16 um 19 53 56" src="https://user-images.githubusercontent.com/11733014/168653740-5765ea0e-18e1-47dc-9b18-90e77db6c0f4.png">

**Comment by DogandElk** [comment]
Hi,
I copied the url from your Cocoapods site i.e https://github.com/SvenTiigi/WhatsNewKit.git <https://github.com/SvenTiigi/WhatsNewKit.git>", from: "1.3.0"

and pasted the url search box box but it doesn't find it, ugh

**Comment by DogandElk** [comment]
I copied the url and pasted it into the searcb bar but it couldn'nt find it
Tom

Tom Glodek
***@***.***
623-258-2079

**Comment by DogandElk** [comment]
I finally went to the git repo and copied that URL and I was able to add the package. 
I then was able to get it to work after struggling with error after error to get it to work in SwiftUI 3 and Xcode 13.3.1. 
I also see that you have case instead a =of a single sheet. Do you have example code for that ?
