### ISSUE TITLE
Prevent the WhatsNew Screen from appearing more than once

### ISSUE THREAD

**Issue by DogandElk** [SvenTiigi/WhatsNewKit#57]
## WhatsNewKit Environment

- WhatsNewKit version: WhatsNewKit 2.0.2
- Xcode version:13.3.1
- Swift version: 5 with SwiftUI 3
- macOS version running Xcode: macOS Monterey Version 12.3.1
- Dependency manager (SPM, Manually): SPM

## What did you do?

> I added the WhatsNew package and used the code for automatic and the WhatsNew  Screen appeared as expected.
## What did you expect to happen?

> I expected the screen to only present once, but when the app was restarted it appeared again.

## What happened instead?

> Every time the app is restarted the whatsnew screen appears.

How do I get the whatsnew screen to appear only once, and not on subsequent restarts of the app until another new version of the app is released and the user updates the app from the App Store ?
Thx

**Comment by SvenTiigi** [comment]
Hi @DogandElk,

could you please provide more information about the `WhatsNewVersionStore` you are using?

Please make sure to use a persistent variant of the `WhatsNewVersionStore` when initializing the environment such as `UserDefaultsWhatsNewVersionStore`

```swift
WhatsNewEnvironment(
    versionStore: UserDefaultsWhatsNewVersionStore(),
    ...
)
```

**Comment by SvenTiigi** [comment]
Closing due inactivity. 
Please feel free to re-open the issue at any time.

**Comment by DogandElk** [comment]
The version that you created for use in a storyboard and UIKIT life cycle is simple and it works just fine, but the version you have for use in swiftUI is so complicated and confusing that it's just not worth the effort to use. Plus you can't use it in a tabView otherwise it just pushes all the info on the screen to the bottom.   Please make a version that works or create a youtube video that shows each and every step that needs to be followed in order to get it to work.

**Comment by DogandElk** [comment]
Perhaps  show how to add a UIViewController to your SwiftUI app

**Comment by DogandElk** [comment]
Thanks for responding.  There seems to be so much conflicting and unclear information on Cocoapods and the reader files that it’s very confusing.   I am building an app in SwiftUI using Xcode 13.3.3 for IOS 15.   Don’t you have a YouTube video on how to implement your package and code it properly.  Otherwise it’s a mind numbing exercise in futility. I need directed information not an encyclopedia of every possible combination.
