### ISSUE TITLE
[Feature] Option to Vertically Center ItemsView

### ISSUE THREAD

**Issue by mattbarker016** [SvenTiigi/WhatsNewKit#6]
Could a configuration be added to potentially center ItemsView? Would help when an app doesn't have too many new features but still want to look good :)

**Comment by SvenTiigi** [comment]
Hey @mattbarker016 

Thanks for your really good idea I like it 🤙

This feature will be implemented for the next release of WhatsNewKit and will be implemented in a separate feature branch [`center-ItemsView`](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/center-ItemsView). 

If you wish you can contribute to this feature branch 🙌

**Comment by SvenTiigi** [comment]
Hey @mattbarker016 

Your feature request has been integrated in Version [`1.1.3`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.1.3) 🙌

**Comment by mattbarker016** [comment]
Awesome!
