### ISSUE TITLE
Ability to remove "already shown entry" from UserDefaults

### ISSUE THREAD

**Issue by blockiyt** [SvenTiigi/WhatsNewKit#64]
### Is your feature request related to a problem?

/

### What solution would you like?

A function in UserDefaultsWhatsNewVersionStore that's called "remove" which simply removes a version from the UserDefaults so that it can be shown again to a user (if he pushes a button)

### What alternatives have you considered?

/

### Any additional context?

/

**Comment by SvenTiigi** [comment]
Hi @blockiyt,

A dedicated [`remove(presentedVersion:)`](https://sventiigi.github.io/WhatsNewKit/documentation/whatsnewkit/userdefaultswhatsnewversionstore/remove(presentedversion:)) function has been added to each default implementation of a WhatsNewVersionStore which is available with the latest release [2.1.0](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/2.1.0)
