### ISSUE TITLE
Display a UIImage

### ISSUE THREAD

**Issue by coldfingersnz** [SvenTiigi/WhatsNewKit#72]
### Is your feature request related to a problem?

Hi, No bugs for me, your kit works well in my apps. 

I was wondering if it was possible to use a UIImage instead of a system icon for a WhatsNew.Feature.

### What solution would you like?

Use a UIImage instead of system icon

### What alternatives have you considered?

I'm pretty new to this so I am a little stuck.

I was thinking it would be something like:

Instead of:
 WhatsNew.Feature(
                    image: .init(systemName: "ladybug"),
                    title: "Cleaned up some Bugs",
                    subtitle: "We have sorted out some minor bugs and UI updates. "
                ),

my feature could be:
 WhatsNew.Feature(
                    image: .init(UIImage: "myImage"),
                    title: "Cleaned up some Bugs",
                    subtitle: "We have sorted out some minor bugs and UI updates. "
                ),

I would be grateful for any help with pointing me in the right direction.

**Comment by SvenTiigi** [comment]
Hi @coldfingersnz,

You can simply use the [`WhatsNew.Feature.Image.init(image:)`](https://github.com/SvenTiigi/WhatsNewKit/blob/1366a8b5855ea97fc52439f68ff29b15846d9403/Sources/Models/WhatsNew%2BFeature%2BImage.swift#L37) initializer and initialize a [`SwiftUI.Image`](https://developer.apple.com/documentation/swiftui/image) with the appropriate [UIImage initializer](https://developer.apple.com/documentation/swiftui/image/init(uiimage:)).

```swift
let image = WhatsNew.Feature.Image(
    image: SwiftUI.Image(
        uiImage: UIImage()
    )
)
```

**Comment by coldfingersnz** [comment]
Fantastic, thanks for the quick response, really appreciate it.
Great Plugin!!
