### ISSUE TITLE
visionOS compability not given

### ISSUE THREAD

**Issue by flexlixrup** [SvenTiigi/WhatsNewKit#75]
### What happened?

Compilation on a visionOS Target is not working due to the following error
`Value of type 'WhatsNewView.FeaturesPadding' has no member 'horizontalSizeClass'`
Right now I have to exclude WhatsNewKit from a dependency of the visionOS platform and add complier directives all over my code

### What are the steps to reproduce?

Add visionOS (native) to a target where WhatsNewKit is listed as a dependency 

### What is the expected behavior?

Compile on visionOS

**Comment by SvenTiigi** [comment]
Hi @flexlixrup,

Support for visionOS is currently not released. 
Please use the [`feature/vision-os-support`](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/vision-os-support) branch which should compile on the visionOS platform.
