### ISSUE TITLE
Avoid presenting for new installation

### ISSUE THREAD

**Issue by MaxMaxP** [SvenTiigi/WhatsNewKit#76]
### Is your feature request related to a problem?

Hi, is it possible to show only if the app is already installed and open? so only after the first update?

### What solution would you like?

-

### What alternatives have you considered?

-

**Comment by SvenTiigi** [comment]
Yes, you can simply subclass the `WhatsNewEnvironment` and implement your very own logic when and how a `WhatsNew` gets presented to a user. Read more [here](https://github.com/SvenTiigi/WhatsNewKit?tab=readme-ov-file#whatsnewenvironment).

**Comment by BlackBird-One** [comment]
Hey Sven, can you add an example. That link is useless to a dumbass.
