### ISSUE TITLE
Multiple updates 

### ISSUE THREAD

**Issue by pkasson** [SvenTiigi/WhatsNewKit#78]
### Is your feature request related to a problem?

Is it possible to show multiple version changes at launch ?

### What solution would you like?

If a user had v1.0 and since then the version is 1.3, is it possible to show what's new with 1.2 AND 1.3 when the app is updated ?

### What alternatives have you considered?

Do not see a way to do this.

### Any additional context?

This is a great tool !

**Comment by SvenTiigi** [comment]
Currently there is no built-in solution for this use case.
