### ISSUE TITLE
exposing the SwiftUI Image in WhatsNew.Feature.Image

### ISSUE THREAD

**Issue by yqiang** [SvenTiigi/WhatsNewKit#79]
### Is your feature request related to a problem?

In addition to showing a sheet, I'm trying to create a simple List view that shows all the updates by enumerating the `WhatsNewItems`. One issue I ran into is that the `WhatsNew.Feature.Image` is essentially a type erased image, so you can't apply Image specific SwiftUI modifiers to it. 

### What solution would you like?

It would be great if somehow the SwiftUI `Image` was exposed so that one can apply Image specific modifiers.

### What alternatives have you considered?

N/A

### Any additional context?

![IMG_E4B431E44BDB-1](https://github.com/SvenTiigi/WhatsNewKit/assets/11876/21b1994c-a30f-4f42-8d73-4f699b7f6a55)

The above is the screen I'm trying to create.

**Comment by SvenTiigi** [comment]
Since the underlying image is retained via a view builder closure there is currently no direct way in retrieving the `SwiftUI.Image` instance.

Please feel free to open up a PR.
