### ISSUE TITLE
Objective-C Support

### ISSUE THREAD

**Issue by ahamedsaifudeen** [SvenTiigi/WhatsNewKit#8]
Can you include an example for using your component on Objective-c?

**Comment by SvenTiigi** [comment]
Hey @ahamedsaifudeen 

Currently `WhatsNewKit` doesn't support Objective-C.

In order to make `WhatsNewKit` compatible with Objective-C a lot of existing code must be refactored. For example all `WhatsNew` structs must be refactored to classes to make them visible in an Objective-C environment.

**Comment by ahamedsaifudeen** [comment]
@SvenTiigi

Understand the complexity. Thanks for quick response.

**Comment by mikemaat** [comment]
If you write yourself a wrapper .swift file, you can use it in an Objective C project (assuming you've already setup support for having both ObjC and Swift in the same project)

![Screenshot 2019-11-06 17 27 11](https://user-images.githubusercontent.com/5282213/68349536-b3485300-00ba-11ea-93fb-cae74c15c49f.png)

![Screenshot 2019-11-06 17 27 45](https://user-images.githubusercontent.com/5282213/68349548-c3f8c900-00ba-11ea-98e7-3aa90eed5755.png)

**Comment by ahamedsaifudeen** [comment]
@mikemaat 

Thanks a lot. This is very helpful. I have added this and it works great.

@SvenTiigi It might be helpful to include this.

**Comment by EpicDraws** [comment]
This works great! You'll just need to create this as WhatsNewObjcWrapper.swift, then import <YourModuleName>-Swift.h (which is autogenerated by Xcode).

In case this saves anyone time, here is the code from the image above in copy/pastable text form:

```
import Foundation
import WhatsNewKit

@objc class WhatsNewObjcWrapper: UIViewController {
    @objc static func getWhatsNewViewController() -> UIViewController {
        let whatsNew = WhatsNew(title: "New in Forecast Bar!",
                                items: [
                                    WhatsNew.Item(
                                        title: "<Your Title>",
                                        subtitle: "Your Description",
                                        image: UIImage(named: "your-image")
                                    ),
                                    WhatsNew.Item(
                                        title: "<Your Title>",
                                        subtitle: "Your Description",
                                        image: UIImage(named: "your-image")
                                    ),
                                    WhatsNew.Item(
                                        title: "<Your Title>",
                                        subtitle: "Your Description",
                                        image: UIImage(named: "your-image")
                                    ),
                                ]
        )
        
        let whatsNewViewController = WhatsNewViewController(whatsNew: whatsNew)
        
        return whatsNewViewController
    }
}


UIViewController* whatsNewController = [WhatsNewObjcWrapper getWhatsNewViewController];
    [self.navigationController presentViewController:whatsNewController animated:true completion:nil];
```
