### ISSUE TITLE
Localized Title gets not displayed in sheet when (empty String) is selected in Localizable.xcstrings file

### ISSUE THREAD

**Issue by flexlixrup** [SvenTiigi/WhatsNewKit#80]
### What happened?

The title of a new version does not get displayed when (empty String) - no translation is entered in the Localizable.xcstrings
file. 
`WhatsNew(version: "1.1.0", title: WhatsNew.Title(stringLiteral: String(localized: "Version 1.1.0")), features: [v1101, v1011])`

While the description (empty String) in the  Localizable.xcstrings would suggest that this is expected behaviour, other SwiftUI components handle it with displaying the text in the base language.

### What are the steps to reproduce?

Create a WhatsNew Object with a localised title. Leave the localisation empty. See the missing title.

### What is the expected behavior?

Displaying the title in the base language.

**Comment by SvenTiigi** [comment]
Closing this as the described issue does not fall in the responsibility of this framework.
