### ISSUE TITLE
Apple review warning ITMS-91053 problem handling

### ISSUE THREAD

**Issue by caosuyang** [SvenTiigi/WhatsNewKit#81]
### Is your feature request related to a problem?

Describing use of required reason API.

ITMS-91053: Missing API declaration - Your app’s code in the “--” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

### What solution would you like?

Add a PrivacyInfo.xcprivacy file and the following information to the Privacy Accessed API Types section

Privacy Accessed API Type: User Defaults

### What alternatives have you considered?

Not yet

**Comment by MDStebel** [comment]
Will this be addressed before May 1st?

**Comment by SvenTiigi** [comment]
A corresponding PrivacyInfo manifest file has been added and is available with the latest release [`2.2.1`](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/2.2.1) ✌️
