### ISSUE TITLE
How did you make the icon for this kit?

### ISSUE THREAD

**Issue by wannafedor4** [SvenTiigi/WhatsNewKit#82]
### Is your feature request related to a problem?

No

### What solution would you like?

An answer

### What alternatives have you considered?

GIMP

### Any additional context?

I googled it a lot

I don’t know where to ask this, but I am making a kit of my own.

**Comment by SvenTiigi** [comment]
Here is the base SVG file I used:
https://raw.githubusercontent.com/sammysmallman/OSCKit/3.x/osckit-icon.svg

**Comment by wannafedor4** [comment]
@SvenTiigi thanks!
