### ISSUE TITLE
Background color surrounding primary action button does not match rest of background color

### ISSUE THREAD

**Issue by gaw3** [SvenTiigi/WhatsNewKit#85]
### What happened?

![RocketSim_Screenshot_iPhone_15_6 1_2024-05-18_12 40 01](https://github.com/SvenTiigi/WhatsNewKit/assets/7268555/213b4de0-4c09-45f4-a3d8-09c038cbce85)

The background color around the feature is black, but the background color around the primary action button is dark grey.

### What are the steps to reproduce?

Step 1:  Generate What's New using the WhatsNewViewController (I am upgrading from 1.3.7 to current, don't know any SwiftUI yet).

### What is the expected behavior?

I expected that the entire WhatsNew background color would be black

**Comment by SvenTiigi** [comment]
Hi @gaw3,

The background around the primary action button is covered with a `UIVisualEffectView` that creates a similar UI/UX to Apple's design. This allows the list to scroll under the visual effect view, blurring the content.

https://github.com/SvenTiigi/WhatsNewKit/blob/6157c77e8be9b3d2310bc680681b61a8d9e290ac/Sources/View/WhatsNewView.swift#L97-L102

Currently, there is no option to configure, disable, or remove this visual effect view.
Please feel free to open a PR.

**Comment by SvenTiigi** [comment]
Closing due inactivity.
Please feel free to re-open the issue at any time.
