### ISSUE TITLE
Secondary action: show actionSheet?

### ISSUE THREAD

**Issue by john-work-ios** [SvenTiigi/WhatsNewKit#87]
### Is your feature request related to a problem?

I'm trying to show an actionSheet for the secondary action.
I tried in UIKit: problem: I don't have a reference to the button to have a sourceView & sourceRect on iPad
I tried in SwiftUI: I could not manage to show an actionSheet, only present a fullView

Any way to achieve this? I would not have thought it to be so complicated at first. Thanks!

### What solution would you like?

N/A

### What alternatives have you considered?

N/A

**Comment by SvenTiigi** [comment]
Hi @john-work-ios,

adding an action sheet directly on the secondary button is currently not possible / supported.

**Comment by john-work-ios** [comment]
Hi @SvenTiigi,

thanks for the feedback. The use case, which I think is interesting is that the secondary button is "Follow the app on...", and the actionSheet let the user choose the social media.

Thanks!
